### ISSUE TITLE
Streamlit app improvements

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/ai-intro-workshop#2]
To improve in the app:

- [x] How the buttons are triggering the model predictions and the generation of molecules
- [x] Ensure no duplicate molecules appear in the generation step
- [x] Make graphs of prediction values
- [x] Implement LLM
- [x] Synthesis planning debug ChemCrow or change tool

**Comment by miquelduranfrigola** [comment]
Quick update - I might do synthesis planning with Aizynthfinder (model [eos526j](https://github.com/ersilia-os/eos526j))

**Comment by GemmaTuron** [comment]
In this [commit](https://github.com/ersilia-os/ai-intro-workshop/commit/cbf79ba2306c905b4188b5987c4bcdedf6dbfb28) I have implemented all the changes, including
- moving the graphs to altair for better images
- adding the necessary graphs
- adding dependencies in the dockerfile for deployment
- making sure the buttons run in the right order 
We are only missing the synth acc if we want to add it @miquelduranfrigola

**Comment by miquelduranfrigola** [comment]
Hi @GemmaTuron I did not succeed with retrosynthetic accessibility, not with RXN from IBM and not with AiZynthFinder. I have come up with something alternative using ChemSpace.

**Comment by miquelduranfrigola** [comment]
@GemmaTuron please feel free to close this issue when you consider it done.

**Comment by GemmaTuron** [comment]
This [commit](https://github.com/ersilia-os/ai-intro-workshop/commit/e633eb911e6e61ed5b1ae4e470e87d4e36d4cab8) closes this issue.
