### ISSUE TITLE
Deploy AI workshop app for public access

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ai-intro-workshop#3]
At the moment, the `ai-intro-workshop` StreamLit app contains a `.do` folder to deploy it in DigitalOcean.
I would go for this option but I would provide sufficient resources so that we are 100% it won't crash during the workshop.

Another option would be to deploy it on AWS ECS, although in this case it will be a bit more involved since we do not have the image per se.

**Comment by GemmaTuron** [comment]
This is done but temporarily because the models are not up any more until we deploy the full platform.
