### ISSUE TITLE
Edit README file (and rename repository?)

### ISSUE THREAD

**Issue by miquelduranfrigola** [ersilia-os/ai-intro-workshop#4]
We should be editing the README file to this repo. At the moment it is mostly empty.

Also, I wonder if we want to rename it to something more specific, for example, `ai2050-h3d-symposium-workshop`

**Comment by GemmaTuron** [comment]
This is completed!
The repo will remain "static" and the app is no longer deployed. Unless we get a specific request to deliver it.
